# Generated by Django 3.0.7 on 2021-04-25 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('bio', models.TextField()),
                ('picture', models.ImageField(blank=True, default='/people/default.jpg', upload_to='people/authors', verbose_name='Author Image')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('book_cover', models.ImageField(blank=True, default='/books/default.jpg', upload_to='books', verbose_name='Book Cover')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Author')),
                ('genre', models.ManyToManyField(to='core.Genre')),
            ],
        ),
    ]
